import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { 
  AiFillGithub, 
  AiFillLinkedin 
} from "react-icons/ai";
import Image from "next/image";
import devth from '../public/dev-thomas.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import Link from 'next/link';
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Thomas Verdam Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">thverdam</h1>
            <ul className="flex  items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white"/>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2 text-teal-400 font-medium md:text-6xl">
              Thomas Verdam
            </h2>
            <h3 className="text-xl py-2 md:text-3xl dark:text-white">Designer e desenvolvedor.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              Freelancer atuando na área de programação e design. Entre em contato comigo e vamos trabalhar!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-8 py-3 text-gray-600 dark:text-gray-400">
            <Link href={"https://github.com/thverdam"}>
              <AiFillGithub />
            </Link>
            <Link href={"https://www.linkedin.com/in/thomas-verdam/"}>
              <AiFillLinkedin />
            </Link>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 md:h-96 md:w-96">
            <Image src={devth} />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Serviços que ofereço</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Desde o meu começo como um designer e desenvolvedor freelancer tenho feito trabalhos
              para <span className="text-teal-500">empresas</span> e <span className="text-teal-500">pequenos negócios</span>, 
              também trabalhei com pessoas talentosas para a criação de interfaces de qualidade.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Eu ofereço os serviços de design de marcas, UI/UX e programação.
            </p>
          </div>
          <div className= "lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image className="mx-auto" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Designs Modernos
              </h3>
              <p className="py-2">
                Faço designs elegantes se encaixando nas suas necessidades seguindo os princípios do design.
              </p>
              <h4 className="py-4 text-teal-600">Ferramentas que uso</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Programação
              </h3>
              <p className="py-2">
                Amo programação e estou em busca de aprender mais sobre a área pra contribuir mais executando esse serviço.
              </p>
              <h4 className="py-4 text-teal-600">Linguagens</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">Java</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image className="mx-auto" src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Consultas
              </h3>
              <p className="py-2">
                Está inseguro com seu projeto? me mande para que tenha uma opinião externa e ter a resposta que precisa!
              </p>
              <h4 className="py-4 text-teal-600">Conhecimentos sobre</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">UI/UX</p>
              <p className="text-gray-800 py-1">CSS</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Clique e dê uma olhada nos meus trabalhos mais recentes
             </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <Link 
              href={"https://www.figma.com/file/OJKlSspsHmdXpwk8OWoFnJ/Littera?node-id=0%3A1&t=Rkdj7PX3iozH6836-1"} 
              className="basis-1/3 flex-1"
            >
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} />
            </Link>
            <Link 
              href={"https://www.figma.com/file/oTFErRcPOi0WZ3k60GTjMi/Fortcon?node-id=1%3A2&t=q10BlM8vnkKcULaK-1"} 
              className="basis-1/3 flex-1"
            >
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} />
            </Link>
            <Link 
              href={"https://www.figma.com/file/rXmDs3J5RImh0nAr3oUW8a/Solucionare?node-id=0%3A1&t=cORJpyqEtThxH3ma-1"} 
              className="basis-1/3 flex-1"
            >
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} />
            </Link>
            <Link 
              href={"https://www.figma.com/file/xqE9fZkj4RFTYNXWBqMBTZ/FV-Publi_Li-on-Tech?t=cORJpyqEtThxH3ma-1"} 
              className="basis-1/3 flex-1"
            >
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} />
            </Link>
          </div>
        </section>
      </main>
    </div>
  )
}
